[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Alexandre Delanoy <al.delanoy@pm.me>"]
publish = false

[workspace]
resolver = "3"
members = [
    "crates/kinaro",
    "crates/ki_project",
    "crates/ki_settings",
    "crates/ki_assets",
    "crates/ki_log",
    "crates/ki_utils",
]
default-members = ["crates/kinaro"]

[workspace.dependencies]
## Internals
ki_project = { path = "crates/ki_project" }
ki_settings = { path = "crates/ki_settings" }
ki_assets = { path = "crates/ki_assets" }
ki_log = { path = "crates/ki_log" }
ki_utils = {path = "crates/ki_utils"}

gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", branch = "main" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version = "*", features = ["serde"] }
thiserror = "2"
anyhow = "1"
log = "0.4"
dirs = "6"
