[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Alexandre Delanoy <al.delanoy@pm.me>"]
publish = false

[workspace]
resolver = "3"
members = [
    "crates/kinaro",
    "crates/project_file",
    "crates/settings",
    "crates/kassets",
    "crates/klog",
    "crates/kutils",
]
default-members = ["crates/kinaro"]

[workspace.dependencies]
## Internals
project_file = { path = "crates/project_file" }
settings = { path = "crates/settings" }
kassets = { path = "crates/kassets" }
klog = { path = "crates/klog" }
kutils = {path = "crates/kutils"}

gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version = "*", features = ["serde"] }
thiserror = "2"
anyhow = "1"
log = "0.4"
dirs = "6"
