[package]
name = "ki_project"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
#Internals
ki_utils.workspace = true

# Externals
gpui-kit.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
serde_yaml = "0.9.0"
log = "0.4.29"
