[package]
name = "kinaro"
version = "0.1.0"
edition = "2024"

[dependencies]
#Internals
assets.workspace = true
klog.workspace = true
settings.workspace = true

gpui.workspace = true
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "x11", "wayland", "runtime_shaders"] }
gpui-component.workspace = true
log.workspace = true
dirs.workspace = true