[package]
name = "kworkspace"
version = "0.1.0"
edition = "2024"

[dependencies]
#Internals
project_file.workspace = true
settings.workspace = true

# Externals
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true